// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVDDWdlTYY19mYSmuj4_R1CKjZUR3scE',
    appId: '1:274697223980:web:7b6c7d1c4a23e0b821f689',
    messagingSenderId: '274697223980',
    projectId: 'diary-app-375d4',
    authDomain: 'diary-app-375d4.firebaseapp.com',
    storageBucket: 'diary-app-375d4.appspot.com',
    measurementId: 'G-P74SBVJHP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHygzGd5ByyHUGo3PyfLAGXTis52eLRk',
    appId: '1:274697223980:android:160cc6ce4c47245521f689',
    messagingSenderId: '274697223980',
    projectId: 'diary-app-375d4',
    storageBucket: 'diary-app-375d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_LOBzDekFal7yWvqsvLuKGezpffqPRY',
    appId: '1:274697223980:ios:f417ecc741517ed721f689',
    messagingSenderId: '274697223980',
    projectId: 'diary-app-375d4',
    storageBucket: 'diary-app-375d4.appspot.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_LOBzDekFal7yWvqsvLuKGezpffqPRY',
    appId: '1:274697223980:ios:f417ecc741517ed721f689',
    messagingSenderId: '274697223980',
    projectId: 'diary-app-375d4',
    storageBucket: 'diary-app-375d4.appspot.com',
    iosBundleId: 'com.example.diaryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXVDDWdlTYY19mYSmuj4_R1CKjZUR3scE',
    appId: '1:274697223980:web:0a395f6381c079b121f689',
    messagingSenderId: '274697223980',
    projectId: 'diary-app-375d4',
    authDomain: 'diary-app-375d4.firebaseapp.com',
    storageBucket: 'diary-app-375d4.appspot.com',
    measurementId: 'G-ZFBKB76J4F',
  );

}