final Map<int, String> code = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly couldy",
  3: "Overcast",
  45: "fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  52: "Moderate drizzle",
  53: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm",
  96: "Slight thunderstom with hail",
  99: "Heavy thunderstom with hail",
};