// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB230eNUVd6sHR1Ahtp0yZGpmi05d5-TJc',
    appId: '1:182458683602:web:275e2a09b28c0152f99d0b',
    messagingSenderId: '182458683602',
    projectId: 'flutter-cookbook-f14d5',
    authDomain: 'flutter-cookbook-f14d5.firebaseapp.com',
    storageBucket: 'flutter-cookbook-f14d5.appspot.com',
    measurementId: 'G-MHP8DG3R59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLIOKibLO_a_03t7ceSR2eOaSb0n-K8U',
    appId: '1:182458683602:android:d64e9ee47c5ddb3ff99d0b',
    messagingSenderId: '182458683602',
    projectId: 'flutter-cookbook-f14d5',
    storageBucket: 'flutter-cookbook-f14d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeawVFlTsrhnZDI3XUatTokViJdeNDHvU',
    appId: '1:182458683602:ios:713600a60acfcc45f99d0b',
    messagingSenderId: '182458683602',
    projectId: 'flutter-cookbook-f14d5',
    storageBucket: 'flutter-cookbook-f14d5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeawVFlTsrhnZDI3XUatTokViJdeNDHvU',
    appId: '1:182458683602:ios:8a2e52216950ec2af99d0b',
    messagingSenderId: '182458683602',
    projectId: 'flutter-cookbook-f14d5',
    storageBucket: 'flutter-cookbook-f14d5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
